# Generated by Django 5.1.1 on 2024-11-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("events_title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_time", models.DateTimeField()),
            ],
        ),
    ]
